class TrelloPageLocators:

    Trello_URL = "https://trello.com/"
    Login_Username = "poorani1520@gmail.com"
    Login_Password = "Test@1234"
    BoardName = "Project"
    List2_Name = "In Progress"
    List1_Name = "Not Started"
    List3_Name = "QA"
    List4_Name = "Done"
    Card1_Name = "Card 1"
    Card2_Name = "Card 2"
    Card3_Name = "Card 3"
    Card4_Name = "Card 4"
    CommentText = "I am done"
    Login_Link = "//a[@class='btn btn-sm btn-link text-primary']"
    Username_Textbox = "//input[@id='user']"
    Login_Atlassian_Button = "//input[@id='login']"
    Password_Textbox = "//input[@id='password']"
    Login_Button = "//button[@id='login-submit']"
    Create_Board_Tile = "//li[@data-test-id='create-board-tile']"
    BoardTitle_Textbox = "//input[@data-test-id='create-board-title-input']"
    CreateBoard_Submit_Button = "//button[@data-test-id='create-board-submit-button']"
    ListName_Textbox = "//input[@class='list-name-input']"
    Add_List = "//input[@value='Add list']"
    List_Textbox_Input = "//input[@placeholder='Enter list title…']"
    Add_Card_NotStarted = "//h2[text()='Not Started']//following::div[4]//*[@class='js-add-a-card']"
    CardTitle_Textbox_Input = "//*[@placeholder='Enter a title for this card…']"
    Add_Card = "//*[@value='Add card']"
    EditIcon_Card2 = "//*[@class='list-card-title js-card-name'][text()='Card 2']//preceding::*[@class='icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu'][1]"
    Movelink = "//*[@class='icon-sm icon-move light']"
    Inprogress_Dropdown = "//*[@class='js-select-list']//option[text()='In Progress']"
    Move_Button = "//*[@value='Move']"
    EditIcon_Card3 = "//*[@class='list-card-title js-card-name'][text()='Card 3']//preceding::*[@class='icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu'][1]"
    QA_Dropdown = "//*[@class='js-select-list']//option[text()='QA']"
    Card1 = "//*[@class='list-card-title js-card-name'][text()='Card 1']"
    CardMembers_Link = "//*[@class='button-link js-change-card-members']"
    CurrentMember = "//*[@class='name js-select-member']"
    Comment_Textbox = "//*[@placeholder='Write a comment…']"
    Save_Button = "//*[@value='Save']"